# Generated by Django 4.2.7 on 2023-12-04 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websightings_app', '0003_sighting_skeptic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicius', to='websightings_app.user'),
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='skeptic',
        ),
        migrations.AddField(
            model_name='sighting',
            name='skeptic',
            field=models.ManyToManyField(related_name='sightings', to='websightings_app.user'),
        ),
    ]
